<?php

/**
 * @file
 * Installation file for Restaurant Reservation Demo module.
 */

/**
 * Implements hook_enable().
 */
function restaurant_reservation_demo_enable() {
  Migration::registerMigration('RestaurantReservationMigrateReservations');
}

/**
 * Implements hook_disable().
 */
function restaurant_reservation_demo_disable() {
  Migration::deregisterMigration('RestaurantReservationMigrateReservations');
}
